version: 2

python:
  version: "3.8"
  # Install our python package before building the docs
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

formats:
  - pdf
  - epub
